import { describe, expect, it } from 'vitest';
import { taskManagementMigration } from '@/database/migrations/004-task-management';
import { SubtaskRepository, TagRepository, TaskRepository } from '@/database/repositories';
import { taskProgressService } from '@/features/tasks/services/TaskProgressService';
import { taskFormSchema } from '@/features/tasks/schemas/task-form';
import type { QueryResultRow, SqlBindValue, SqlExecutionResult, SqlExecutor } from '@/types/database';
import type { Subtask, Task } from '@/database/models';

class Database implements SqlExecutor {
  public readonly commands: string[] = []; public readonly parameters: SqlBindValue[][] = []; public rows: QueryResultRow[] = [];
  async execute(sql: string, values: SqlBindValue[] = []): Promise<SqlExecutionResult> { this.commands.push(sql); this.parameters.push(values); return { rowsAffected: 1 }; }
  async select<T extends QueryResultRow>(sql: string, values: SqlBindValue[] = []): Promise<T[]> { this.commands.push(sql); this.parameters.push(values); return this.rows as T[]; }
}
const id = 'c0a8012e-0000-4000-8000-000000000001'; const phaseId = 'c0a8012e-0000-4000-8000-000000000002';
const row: QueryResultRow = { id,phase_id:phaseId,title:'Tarefa',description:'',position:0,status:'not_started',priority:'medium',completed:0,completed_at:null,start_date:null,estimated_minutes:null,spent_minutes:0,due_date:null,assignee:null,created_at:'2026-08-01T00:00:00.000Z',updated_at:'2026-08-01T00:00:00.000Z',deleted_at:null,sync_status:'pending',local_version:1,server_version:0,device_id:'test' };
describe('task management', () => {
  it('applies task columns and indexes through migration 004', async () => { const database = new Database(); await taskManagementMigration.up(database); expect(database.commands.some((sql) => sql.includes('completed_at'))).toBe(true); expect(database.commands.some((sql) => sql.includes('idx_tasks_due_date'))).toBe(true); });
  it('validates task dates and negative time before persistence', () => { expect(() => taskFormSchema.parse({ title:' ',estimatedMinutes:0,spentMinutes:0 })).toThrow(); expect(() => taskFormSchema.parse({ title:'Valida',startDate:'2026-08-10',dueDate:'2026-08-01',estimatedMinutes:0,spentMinutes:0 })).toThrow(); expect(() => taskFormSchema.parse({ title:'Valida',estimatedMinutes:-1,spentMinutes:0 })).toThrow(); });
  it('creates a task with pending synchronization and history', async () => { const database = new Database(); const task = await new TaskRepository(database).create({ id,phaseId,title:'  Tarefa  ',position:0,deviceId:'test' }); expect(task.title).toBe('Tarefa'); expect(task.syncStatus).toBe('pending'); expect(database.commands[0]).toContain('INSERT INTO tasks'); expect(database.parameters.some((values) => values[1] === 'task_created')).toBe(true); });
  it('soft deletes and restores tasks logically', async () => { const database = new Database(); database.rows = [row,{ total:0 }]; const repository = new TaskRepository(database); await repository.softDelete(id); expect(database.commands.some((sql) => sql.includes('UPDATE tasks SET deleted_at'))).toBe(true); database.rows = [row,{ total:0 }]; await repository.restore(id); expect(database.commands.some((sql) => sql.includes('deleted_at=NULL'))).toBe(true); expect(database.parameters.some((values) => values[1] === 'task_restored')).toBe(true); });
  it('moves tasks in a transaction and normalizes positions', async () => { const database = new Database(); database.rows = [row]; await new TaskRepository(database).moveToPhase(id,'c0a8012e-0000-4000-8000-000000000003'); expect(database.commands[1]).toBe('BEGIN'); expect(database.commands).toContain('COMMIT'); expect(database.commands.some((sql) => sql.includes('phase_id=?'))).toBe(true); });
  it('creates, toggles and reorders subtasks', async () => { const database = new Database(); const repository = new SubtaskRepository(database); await repository.create({ taskId:id,title:'Subtarefa',position:0 }); await repository.reorder(id,['a','b']); expect(database.commands.some((sql) => sql.startsWith('INSERT INTO subtasks'))).toBe(true); expect(database.commands).toContain('BEGIN'); expect(database.commands).toContain('COMMIT'); });
  it('prevents duplicate tags without case sensitivity and attaches tags', async () => { const database = new Database(); database.rows = [{ id:'tag' }]; await expect(new TagRepository(database).create('Urgente')).rejects.toThrow('ja existe'); database.rows = []; const tags = new TagRepository(database); await tags.attachToTask(id,'c0a8012e-0000-4000-8000-000000000004'); expect(database.commands.at(-1)).toContain('INSERT OR IGNORE INTO task_tags'); });
  it('calculates task progress from active subtasks', () => { const task = { ...row,id,phaseId,completed:false,createdAt:'',updatedAt:'',deletedAt:null,syncStatus:'pending' as const,localVersion:1,serverVersion:0,deviceId:'test',completedAt:null,startDate:null,estimatedMinutes:null,spentMinutes:0,dueDate:null,assignee:null } as Task; const subtasks = [{ id:'a',taskId:id,title:'A',completed:true,position:0,createdAt:'',updatedAt:'',deletedAt:null,syncStatus:'pending' as const,localVersion:1,serverVersion:0,deviceId:'test' },{ id:'b',taskId:id,title:'B',completed:false,position:1,createdAt:'',updatedAt:'',deletedAt:null,syncStatus:'pending' as const,localVersion:1,serverVersion:0,deviceId:'test' }] satisfies Subtask[]; expect(taskProgressService.calculate(task,subtasks)).toBe(50); expect(taskProgressService.calculate({ ...task,completed:true },subtasks)).toBe(100); });
});
