import { useEffect } from 'react';
import { useSettings } from '@/features/settings/hooks/useSettings';

const translations = {
  en: { overview: 'Overview', projects: 'Projects', archived: 'Archived', trash: 'Trash', settings: 'Settings', about: 'About', foundation: 'Workspace', phase: 'Roadmap planning workspace', localLibrary: 'Local library', newRoadmap: 'New roadmap', searchProjects: 'Search by title, category or version', gridView: 'Grid view', listView: 'List view', results: 'result(s)', loadingRoadmaps: 'Loading roadmaps...', localDataError: 'Could not access local data.', noMatch: 'No project matches your search.', noRoadmaps: 'No roadmaps yet', startOrganizing: 'Create a project to start organizing your work.', aboutEyebrow: 'A clearer way to move work forward', aboutTitle: 'Plan with clarity. Build with confidence.', aboutDescription: 'Roadmap Studio helps you turn ideas into organized, visible progress. Keep projects, phases and tasks together so you always know what matters next.', aboutWorkspace: 'Your focused workspace', aboutWorkspaceDescription: 'Bring priorities, milestones and daily work into one calm, structured view.', aboutProgress: 'Progress you can trust', aboutProgressDescription: 'See what is moving, what is blocked and what still needs attention at a glance.', aboutFlexible: 'Made for the way you work', aboutFlexibleDescription: 'Shape roadmaps around your process with flexible phases, tasks, statuses and priorities.', aboutFeatureTitle: 'Everything important, in one place', aboutFeatureDescription: 'A focused toolkit for planning, executing and reviewing work without unnecessary noise.', featureRoadmaps: 'Roadmaps', featureRoadmapsDescription: 'Organize goals and initiatives with clear ownership and direction.', featureTasks: 'Tasks and phases', featureTasksDescription: 'Break work into practical steps and keep progress visible.', featureFocus: 'Focus and momentum', featureFocusDescription: 'Use the Kanban view and daily priorities to keep moving forward.', aboutVersion: 'Version', aboutMadeFor: 'Built for people who plan, create and deliver.', aboutFooter: 'Roadmap Studio keeps your work close, clear and ready for the next step.' },
  pt: { overview: 'Visão geral', projects: 'Projetos', archived: 'Arquivados', trash: 'Lixeira', settings: 'Configurações', about: 'Sobre', foundation: 'Workspace', phase: 'Workspace de planejamento de roadmaps', localLibrary: 'Biblioteca local', newRoadmap: 'Novo roadmap', searchProjects: 'Buscar por título, categoria ou versão', gridView: 'Visualização em grade', listView: 'Visualização em lista', results: 'resultado(s)', loadingRoadmaps: 'Carregando roadmaps...', localDataError: 'Não foi possível acessar os dados locais.', noMatch: 'Nenhum projeto corresponde à busca.', noRoadmaps: 'Sem roadmaps', startOrganizing: 'Crie um projeto para começar a organizar o trabalho.', aboutEyebrow: 'Uma forma mais clara de fazer o trabalho avançar', aboutTitle: 'Planeje com clareza. Construa com confiança.', aboutDescription: 'O Roadmap Studio ajuda você a transformar ideias em progresso organizado e visível. Mantenha projetos, fases e tarefas juntos para saber sempre o que vem a seguir.', aboutWorkspace: 'Seu workspace focado', aboutWorkspaceDescription: 'Reúna prioridades, marcos e trabalho diário em uma visão calma e estruturada.', aboutProgress: 'Progresso em que você confia', aboutProgressDescription: 'Veja o que está avançando, bloqueado e o que ainda precisa de atenção.', aboutFlexible: 'Feito para o seu jeito de trabalhar', aboutFlexibleDescription: 'Modele os roadmaps ao seu processo com fases, tarefas, status e prioridades flexíveis.', aboutFeatureTitle: 'Tudo que importa, em um só lugar', aboutFeatureDescription: 'Uma ferramenta focada para planejar, executar e revisar o trabalho sem ruído desnecessário.', featureRoadmaps: 'Roadmaps', featureRoadmapsDescription: 'Organize objetivos e iniciativas com direção clara.', featureTasks: 'Tarefas e fases', featureTasksDescription: 'Divida o trabalho em etapas práticas e mantenha o progresso visível.', featureFocus: 'Foco e ritmo', featureFocusDescription: 'Use o Kanban e as prioridades do dia para continuar avançando.', aboutVersion: 'Versão', aboutMadeFor: 'Feito para quem planeja, cria e entrega.', aboutFooter: 'O Roadmap Studio mantém seu trabalho próximo, claro e pronto para o próximo passo.' },
} as const;

type TranslationKey = keyof typeof translations.en;

export function useTranslation() {
  const settings = useSettings();
  const english = settings.data?.language === 'en-US';
  useEffect(() => { document.documentElement.lang = english ? 'en' : 'pt-BR'; }, [english]);
  return { language: english ? 'en-US' : 'pt-BR', t: (key: TranslationKey) => translations[english ? 'en' : 'pt'][key] };
}
