import type { CompletionStats, Subtask } from '@/database/models';
import { RepositoryBase } from '@/database/repositories/RepositoryBase';
import { mapMeta, newMeta, rowValue } from '@/database/repositories/row-mapper';
import { subtaskInputSchema, type SubtaskInput } from '@/schemas/database';
import type { QueryResultRow, SqlExecutor } from '@/types/database';

export class SubtaskRepository extends RepositoryBase<Subtask> {
  constructor(database: SqlExecutor) { super(database, 'subtasks'); }
  protected mapRow(row: QueryResultRow): Subtask { return { ...mapMeta(row), taskId: rowValue.string(row,'task_id'), title: rowValue.string(row,'title'), completed: rowValue.boolean(row,'completed'), position: rowValue.number(row,'position') }; }
  private async history(action: string, id: string, payload: Record<string, unknown> = {}): Promise<void> { const meta = newMeta(undefined, 'local-device'); await this.database.execute('INSERT INTO history (id,action_type,entity_type,entity_id,payload_json,occurred_at,created_at,updated_at,deleted_at,sync_status,local_version,server_version,device_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)', [meta.id,action,'subtask',id,JSON.stringify(payload),meta.createdAt,meta.createdAt,meta.updatedAt,null,'pending',1,0,meta.deviceId]); }
  public async findByTaskId(taskId: string): Promise<Subtask[]> { return this.queryMany('SELECT * FROM subtasks WHERE task_id=? AND deleted_at IS NULL ORDER BY position', [taskId]); }
  public async create(value: SubtaskInput): Promise<Subtask> { const input = subtaskInputSchema.parse(value); const item = { ...newMeta(input.id,input.deviceId), ...input }; await this.database.execute('INSERT INTO subtasks (id,task_id,title,completed,position,created_at,updated_at,deleted_at,sync_status,local_version,server_version,device_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)', [item.id,item.taskId,item.title,item.completed,item.position,item.createdAt,item.updatedAt,item.deletedAt,item.syncStatus,item.localVersion,item.serverVersion,item.deviceId]); await this.history('subtask_created',item.id,{ title:item.title }); return item; }
  public async createAtEnd(taskId: string, title: string): Promise<Subtask> { return this.create({ taskId,title,position:await this.countByTaskId(taskId) }); }
  public async update(id: string, value: Partial<SubtaskInput>): Promise<Subtask | null> { const current = await this.findById(id); if (!current) return null; const input = subtaskInputSchema.parse({ ...current,...value,id,deviceId:current.deviceId }); await this.database.execute("UPDATE subtasks SET title=?,completed=?,position=?,updated_at=?,sync_status='pending',local_version=local_version+1 WHERE id=?", [input.title,input.completed,input.position,new Date().toISOString(),id]); await this.history('subtask_updated',id); return this.findById(id); }
  public async toggleCompleted(id: string): Promise<void> { const item = await this.findById(id); if (!item) return; await this.database.execute("UPDATE subtasks SET completed=?,updated_at=?,sync_status='pending',local_version=local_version+1 WHERE id=?", [!item.completed,new Date().toISOString(),id]); await this.history(item.completed ? 'subtask_reopened' : 'subtask_completed',id); }
  public async reorder(taskId: string, orderedSubtaskIds: string[]): Promise<void> { await this.database.execute('BEGIN'); try { for (const [position,id] of orderedSubtaskIds.entries()) await this.database.execute("UPDATE subtasks SET position=?,updated_at=?,sync_status='pending',local_version=local_version+1 WHERE id=? AND task_id=?", [position,new Date().toISOString(),id,taskId]); await this.history('subtask_reordered',taskId,{ subtaskIds:orderedSubtaskIds }); await this.database.execute('COMMIT'); } catch (error) { await this.database.execute('ROLLBACK'); throw error; } }
  public async softDelete(id: string): Promise<void> { await this.delete(id); await this.history('subtask_soft_deleted',id); }
  public async restore(id: string): Promise<void> { await this.database.execute("UPDATE subtasks SET deleted_at=NULL,updated_at=?,sync_status='pending',local_version=local_version+1 WHERE id=?", [new Date().toISOString(),id]); await this.history('subtask_restored',id); }
  public async permanentDelete(id: string): Promise<void> { await this.database.execute('DELETE FROM subtasks WHERE id=?',[id]); }
  public async countByTaskId(taskId: string): Promise<number> { const rows = await this.database.select<QueryResultRow>('SELECT COUNT(*) total FROM subtasks WHERE task_id=? AND deleted_at IS NULL',[taskId]); return rowValue.number(rows[0] ?? {},'total'); }
  public async getCompletionStats(taskId: string): Promise<CompletionStats> { const rows = await this.database.select<QueryResultRow>('SELECT COUNT(*) total,SUM(completed=1) completed FROM subtasks WHERE task_id=? AND deleted_at IS NULL',[taskId]); return { total:rowValue.number(rows[0] ?? {},'total'),completed:rowValue.number(rows[0] ?? {},'completed') }; }
}
