import { useMemo, useState } from 'react';
import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { ListFilter, Plus, Search } from 'lucide-react';
import type { Phase, Task } from '@/database/models';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { useToast } from '@/components/feedback/useToast';
import { TaskCard } from '@/features/tasks/components/TaskCard';
import { TaskPanel } from '@/features/tasks/components/TaskPanel';
import { useDeletedTasks, useSubtasks, useTaskActions, useTaskStats, useTaskTags, useTasks } from '@/features/tasks/hooks/useTasks';
import { taskProgressService } from '@/features/tasks/services/TaskProgressService';
import { useTaskUiStore } from '@/store/task-ui/task-ui-store';
import type { TaskFormValues } from '@/features/tasks/schemas/task-form';
import { useTranslation } from '@/i18n/useTranslation';

function SortableTask({ task, compact, onOpen, onToggle, onDelete }: { task: Task; compact: boolean; onOpen: () => void; onToggle: () => void; onDelete: () => void }) { const sort = useSortable({ id:task.id }); const subtasks = useSubtasks(task.id); const tags = useTaskTags(task.id); return <div ref={sort.setNodeRef} style={{ transform:CSS.Transform.toString(sort.transform),transition:sort.transition }}><TaskCard task={task} tags={tags.data ?? []} compact={compact} subtaskProgress={taskProgressService.calculate(task,subtasks.data ?? [])} dragAttributes={sort.attributes} dragListeners={sort.listeners} onOpen={onOpen} onToggle={onToggle} onDelete={onDelete} /></div>; }
const newTask: TaskFormValues = { title:'Nova tarefa',description:'',status:'not_started',priority:'medium',startDate:null,dueDate:null,estimatedMinutes:null,spentMinutes:0,assignee:null };
export function TaskList({ phase, phases }: { phase: Phase; phases: Phase[] }) {
  const { language } = useTranslation(); const english = language === 'en-US';
  const ui = useTaskUiStore(); const [query,setQuery] = useState(''); const [selected,setSelected] = useState<Task | null>(null); const filters = useMemo(() => ({ ...ui.filters,query }),[ui.filters,query]); const tasks = useTasks(phase.id,filters); const deleted = useDeletedTasks(phase.id); const stats = useTaskStats(phase.id); const actions = useTaskActions(phase.id); const toast = useToast(); const sensors = useSensors(useSensor(PointerSensor),useSensor(KeyboardSensor,{ coordinateGetter:sortableKeyboardCoordinates }));
  const reorder = ({ active,over }: DragEndEvent) => { if (!over || active.id === over.id || ui.filters.sort && ui.filters.sort !== 'position') return; const current = tasks.data ?? []; const from=current.findIndex((task) => task.id===active.id); const to=current.findIndex((task) => task.id===over.id); const next=[...current]; next.splice(to,0,next.splice(from,1)[0]!); actions.reorder.mutate(next.map((task) => task.id),{ onError:() => toast.show(english ? 'Could not reorder tasks.' : 'Nao foi possivel reordenar as tarefas.','error') }); };
  const statusLabels = english ? { all: 'All statuses', progress: 'In progress', blocked: 'Blocked', completed: 'Completed' } : { all: 'Todos os status', progress: 'Em andamento', blocked: 'Bloqueadas', completed: 'Concluidas' };
  return <section className="mt-4 rounded-lg border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{english ? 'Phase tasks' : 'Tarefas da fase'}</h2><p className="text-xs text-muted-foreground">{stats.data?.completed ?? 0}/{stats.data?.total ?? 0} {english ? 'completed' : 'concluidas'}, {stats.data?.overdue ?? 0} {english ? 'overdue' : 'atrasadas'}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" aria-label={english ? 'Toggle compact mode' : 'Alternar modo compacto'} onClick={() => ui.setCompact(!ui.compact)}><ListFilter className="h-4 w-4" /></Button><Button size="sm" onClick={() => actions.create.mutate(newTask,{ onSuccess:(task) => { setSelected(task); toast.show(english ? 'Task created.' : 'Tarefa criada.'); } })}><Plus className="h-4 w-4" />{english ? 'Add task' : 'Adicionar tarefa'}</Button></div></div><div className="mt-4 flex flex-wrap gap-2"><div className="relative min-w-56 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={english ? 'Search tasks' : 'Buscar tarefas'} /></div><select className="rounded-lg border bg-background px-2 text-sm" value={ui.filters.status ?? ''} onChange={(event) => ui.setFilters({ ...ui.filters,status:event.target.value || undefined })}><option value="">{statusLabels.all}</option><option value="in_progress">{statusLabels.progress}</option><option value="blocked">{statusLabels.blocked}</option><option value="completed">{statusLabels.completed}</option></select><select className="rounded-lg border bg-background px-2 text-sm" value={ui.filters.sort ?? 'position'} onChange={(event) => ui.setFilters({ ...ui.filters,sort:event.target.value as NonNullable<typeof ui.filters.sort> })}><option value="position">{english ? 'Manual order' : 'Ordem manual'}</option><option value="due_date">{english ? 'Due date' : 'Prazo'}</option><option value="priority">{english ? 'Priority' : 'Prioridade'}</option><option value="updated_at">{english ? 'Updated' : 'Atualizacao'}</option><option value="title">{english ? 'Title' : 'Titulo'}</option></select>{Object.keys(ui.filters).length > 1 ? <Button size="sm" variant="ghost" onClick={ui.clearFilters}>{english ? 'Clear filters' : 'Limpar filtros'}</Button> : null}</div>
    {tasks.isLoading ? <p className="py-8 text-center text-sm text-muted-foreground">{english ? 'Loading tasks...' : 'Carregando tarefas...'}</p> : !tasks.data?.length ? <div className="py-10 text-center"><p className="font-medium">{query ? (english ? 'No tasks found.' : 'Nenhuma tarefa encontrada.') : (english ? 'This phase has no tasks yet.' : 'Esta fase ainda nao possui tarefas.')}</p><p className="mt-1 text-sm text-muted-foreground">{query ? (english ? 'Adjust your filters or search.' : 'Ajuste os filtros ou a busca.') : (english ? 'Create the first task to turn planning into action.' : 'Crie a primeira tarefa para transformar o planejamento em acao.')}</p></div> : <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={reorder}><SortableContext items={tasks.data.map((task) => task.id)} strategy={verticalListSortingStrategy}><div className="mt-4 space-y-2">{tasks.data.map((task) => <SortableTask key={task.id} task={task} compact={ui.compact} onOpen={() => setSelected(task)} onToggle={() => actions.toggle.mutate(task.id,{ onSuccess:() => toast.show(task.completed ? (english ? 'Task reopened.' : 'Tarefa reaberta.') : (english ? 'Task completed.' : 'Tarefa concluida.')) })} onDelete={() => actions.remove.mutate(task.id,{ onSuccess:() => toast.show(english ? 'Task moved to trash.' : 'Tarefa movida para a lixeira.') })} />)}</div></SortableContext></DndContext>}
    <TaskPanel task={selected} phases={phases} saving={actions.update.isPending} onClose={() => setSelected(null)} onSave={(values) => selected && actions.update.mutate({ id:selected.id,values },{ onSuccess:() => toast.show(english ? 'Task saved.' : 'Tarefa salva.') })} onMove={(targetPhaseId) => selected && actions.move.mutate({ taskId:selected.id,targetPhaseId },{ onSuccess:() => { setSelected(null); toast.show(english ? 'Task moved.' : 'Tarefa movida.'); } })} />
    {deleted.data?.length ? <section className="mt-5 border-t pt-4"><h3 className="text-sm font-semibold">{english ? 'Deleted tasks' : 'Tarefas excluidas'}</h3><div className="mt-2 space-y-2">{deleted.data.map((task) => <div key={task.id} className="flex items-center justify-between gap-3 text-sm"><span className="truncate">{task.title}</span><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => actions.restore.mutate(task.id,{ onSuccess:() => toast.show(english ? 'Task restored.' : 'Tarefa restaurada.') })}>{english ? 'Restore' : 'Restaurar'}</Button><Button size="sm" variant="destructive" onClick={() => actions.permanentDelete.mutate(task.id,{ onSuccess:() => toast.show(english ? 'Task permanently deleted.' : 'Tarefa excluida permanentemente.') })}>{english ? 'Delete' : 'Excluir'}</Button></div></div>)}</div></section> : null}
  </section>;
}
