import { useEffect, useState } from 'react';
import { X } from 'lucide-react';
import type { Phase, Task } from '@/database/models';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/Tabs';
import { useSubtaskActions, useSubtasks, useTaskHistory, useTaskTagActions, useTaskTags } from '@/features/tasks/hooks/useTasks';
import { taskPriorities, taskStatuses } from '@/features/tasks/types/task';
import type { TaskFormValues } from '@/features/tasks/schemas/task-form';
import { taskStatusMeta, taskPriorityMeta } from '@/features/tasks/types/task';
import { useTranslation } from '@/i18n/useTranslation';

interface Props { task: Task | null; phases: Phase[]; saving: boolean; onClose: () => void; onSave: (values: TaskFormValues) => void; onMove: (targetPhaseId: string) => void; }
const defaults: TaskFormValues = { title: '', description: '', status: 'not_started', priority: 'medium', startDate: null, dueDate: null, estimatedMinutes: null, spentMinutes: 0, assignee: null };
export function TaskPanel({ task, phases, saving, onClose, onSave, onMove }: Props) {
  const { language } = useTranslation(); const english = language === 'en-US';
  const [values,setValues] = useState<TaskFormValues>(defaults); const [subtaskTitle,setSubtaskTitle] = useState(''); const [tagName,setTagName] = useState('');
  const subtasks = useSubtasks(task?.id ?? ''); const subtaskActions = useSubtaskActions(task?.id ?? ''); const tags = useTaskTags(task?.id ?? ''); const tagActions = useTaskTagActions(task?.id ?? ''); const history = useTaskHistory(task?.id ?? '');
  useEffect(() => { if (task) setValues({ title:task.title,description:task.description,status:task.status as TaskFormValues['status'],priority:task.priority as TaskFormValues['priority'],startDate:task.startDate,dueDate:task.dueDate,estimatedMinutes:task.estimatedMinutes,spentMinutes:task.spentMinutes,assignee:task.assignee }); },[task]);
  if (!task) return null; const change = <K extends keyof TaskFormValues>(key: K, value: TaskFormValues[K]) => setValues((current) => ({ ...current,[key]:value }));
  return <aside className="fixed inset-y-0 right-0 z-50 w-full max-w-xl overflow-y-auto border-l bg-background p-5 shadow-xl" role="dialog" aria-label={english ? 'Task details' : 'Detalhes da tarefa'}>
    <div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">{english ? 'Task details' : 'Detalhes da tarefa'}</h2><Button size="icon" variant="ghost" aria-label={english ? 'Close panel' : 'Fechar painel'} onClick={onClose}><X className="h-5 w-5" /></Button></div>
    <Tabs defaultValue="general"><TabsList className="w-full justify-start overflow-x-auto"><TabsTrigger value="general">{english ? 'General' : 'Geral'}</TabsTrigger><TabsTrigger value="subtasks">{english ? 'Subtasks' : 'Subtarefas'}</TabsTrigger><TabsTrigger value="time">{english ? 'Dates and time' : 'Datas e tempo'}</TabsTrigger><TabsTrigger value="tags">Tags</TabsTrigger><TabsTrigger value="history">{english ? 'History' : 'Historico'}</TabsTrigger></TabsList>
      <TabsContent value="general" className="space-y-3"><label className="block text-sm">{english ? 'Title' : 'Titulo'}<Input value={values.title} onChange={(event) => change('title',event.target.value)} /></label><label className="block text-sm">{english ? 'Description' : 'Descricao'}<textarea className="mt-1 min-h-28 w-full rounded-lg border bg-background p-2" value={values.description} onChange={(event) => change('description',event.target.value)} /></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">Status<select className="mt-1 h-10 w-full rounded-lg border bg-background px-2" value={values.status} onChange={(event) => change('status',event.target.value as TaskFormValues['status'])}>{taskStatuses.map((status) => <option key={status} value={status}>{english ? ({ backlog:'Backlog', planned:'Planned', not_started:'Not started', in_progress:'In progress', blocked:'Blocked', in_review:'In review', completed:'Completed', cancelled:'Cancelled' } as Record<string,string>)[status] : taskStatusMeta[status].label}</option>)}</select></label><label className="text-sm">{english ? 'Priority' : 'Prioridade'}<select className="mt-1 h-10 w-full rounded-lg border bg-background px-2" value={values.priority} onChange={(event) => change('priority',event.target.value as TaskFormValues['priority'])}>{taskPriorities.map((priority) => <option key={priority} value={priority}>{english ? ({ low:'Low', medium:'Medium', high:'High', critical:'Critical' } as Record<string,string>)[priority] : taskPriorityMeta[priority].label}</option>)}</select></label></div><label className="block text-sm">{english ? 'Assignee' : 'Responsavel'}<Input value={values.assignee ?? ''} onChange={(event) => change('assignee',event.target.value || null)} /></label><label className="block text-sm">{english ? 'Phase' : 'Fase'}<select className="mt-1 h-10 w-full rounded-lg border bg-background px-2" value={task.phaseId} onChange={(event) => event.target.value !== task.phaseId && onMove(event.target.value)}>{phases.map((phase) => <option key={phase.id} value={phase.id}>{phase.title}</option>)}</select></label><Button className="w-full" disabled={saving} onClick={() => onSave(values)}>{saving ? (english ? 'Saving...' : 'Salvando...') : (english ? 'Save changes' : 'Salvar alteracoes')}</Button></TabsContent>
      <TabsContent value="subtasks"><div className="flex gap-2"><Input value={subtaskTitle} placeholder={english ? 'New subtask' : 'Nova subtarefa'} onChange={(event) => setSubtaskTitle(event.target.value)} /><Button onClick={() => { if (subtaskTitle.trim()) { subtaskActions.create.mutate(subtaskTitle.trim()); setSubtaskTitle(''); } }}>{english ? 'Add' : 'Adicionar'}</Button></div><ul className="mt-4 space-y-2">{subtasks.data?.map((subtask) => <li key={subtask.id} className="flex items-center gap-2 border-b pb-2"><input type="checkbox" checked={subtask.completed} aria-label={`${english ? 'Complete' : 'Concluir'} ${subtask.title}`} onChange={() => subtaskActions.toggle.mutate(subtask.id)} /><span className={subtask.completed ? 'line-through text-muted-foreground' : ''}>{subtask.title}</span></li>)}</ul></TabsContent>
      <TabsContent value="time" className="space-y-3"><div className="grid grid-cols-2 gap-3"><label className="text-sm">{english ? 'Start' : 'Inicio'}<Input type="date" value={values.startDate ?? ''} onChange={(event) => change('startDate',event.target.value || null)} /></label><label className="text-sm">{english ? 'Due date' : 'Prazo'}<Input type="date" value={values.dueDate ?? ''} onChange={(event) => change('dueDate',event.target.value || null)} /></label></div><label className="block text-sm">{english ? 'Estimate (minutes)' : 'Estimativa (minutos)'}<Input type="number" min="0" value={values.estimatedMinutes ?? ''} onChange={(event) => change('estimatedMinutes',event.target.value ? Number(event.target.value) : null)} /></label><label className="block text-sm">{english ? 'Time spent (minutes)' : 'Tempo gasto (minutos)'}<Input type="number" min="0" value={values.spentMinutes} onChange={(event) => change('spentMinutes',Number(event.target.value))} /></label></TabsContent>
      <TabsContent value="tags"><div className="flex gap-2"><Input value={tagName} placeholder={english ? 'Create tag' : 'Criar tag'} onChange={(event) => setTagName(event.target.value)} /><Button onClick={() => { if (tagName.trim()) { tagActions.create.mutate({ name:tagName.trim(),color:'#2563EB' }, { onSuccess: (tag) => tagActions.attach.mutate(tag.id) }); setTagName(''); } }}>{english ? 'Create' : 'Criar'}</Button></div><div className="mt-4 flex flex-wrap gap-2">{tags.data?.map((tag) => <button key={tag.id} className="rounded px-2 py-1 text-xs text-white" style={{ backgroundColor:tag.color }} onClick={() => tagActions.detach.mutate(tag.id)}>{tag.name} x</button>)}</div></TabsContent>
      <TabsContent value="history">{history.isLoading ? <p className="text-sm text-muted-foreground">{english ? 'Loading history...' : 'Carregando historico...'}</p> : history.data?.length ? <ul className="space-y-3">{history.data.map((item,index) => <li key={`${String(item.occurred_at)}-${index}`} className="border-b pb-2 text-sm"><p className="font-medium">{String(item.action_type)}</p><p className="text-xs text-muted-foreground">{new Date(String(item.occurred_at)).toLocaleString(english ? 'en-US' : 'pt-BR')}</p></li>)}</ul> : <p className="text-sm text-muted-foreground">{english ? 'No changes recorded.' : 'Nenhuma alteracao registrada.'}</p>}</TabsContent>
    </Tabs>
  </aside>;
}
