import { useMemo, useState, type ElementType } from 'react';
import { Bell, CheckCircle2, Clock3, FileJson, FolderArchive, FolderKanban, Gauge, Goal, Heart, LayoutDashboard, ListTodo, Plus, Settings2, Star, Target, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/Card';
import { categoryBadgeMeta, priorityBadgeMeta, progressBadgeMeta, statusBadgeMeta } from '@/features/badges/constants/badge-catalog';
import { useDashboardInsights } from '@/features/dashboard/hooks/useDashboardInsights';
import { useDashboardModules } from '@/features/dashboard/hooks/useDashboardModules';
import { dashboardModuleLabels, type DashboardPeriod } from '@/features/dashboard/types/dashboard';
import { useDashboardData } from '@/features/roadmap-management/hooks/useRoadmaps';
import { useTranslation } from '@/i18n/useTranslation';

function Module({ title, description, children, className = '' }: { title: string; description?: string; children: React.ReactNode; className?: string }) {
  return <Card className={`animate-in fade-in-0 slide-in-from-bottom-2 duration-300 ${className}`}><CardHeader className="pb-3"><CardTitle className="text-base">{title}</CardTitle>{description ? <CardDescription>{description}</CardDescription> : null}</CardHeader><CardContent>{children}</CardContent></Card>;
}

function Stats({ loading, cards }: { loading: boolean; cards: Array<{ label: string; value: number; icon: ElementType; description: string }> }) {
  return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{cards.map(({ label, value, icon: Icon, description }) => <Card key={label} className="transition-all duration-150 hover:scale-[1.02] hover:shadow-soft"><CardContent className="flex min-h-28 flex-col justify-between gap-3 p-4"><div className="flex items-center justify-between"><span className="rounded-lg bg-primary/10 p-2 text-primary"><Icon className="h-4 w-4" /></span><span className="text-2xl font-semibold tabular-nums">{loading ? '-' : value}</span></div><div><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs text-muted-foreground">{description}</p></div></CardContent></Card>)}</div>;
}

function Productivity({ activity, english }: { activity: Array<{ date: string; count: number }>; english: boolean }) {
  const byDate = new Map(activity.map((item) => [item.date, item.count]));
  const days = Array.from({ length: 35 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (34 - index)); const key = date.toISOString().slice(0, 10); return { key, count: byDate.get(key) ?? 0 }; });
  return <><div className="grid grid-cols-7 gap-1.5" aria-label={english ? 'Daily activity' : 'Atividade diária'}>{days.map(({ key, count }) => <span key={key} title={`${new Date(`${key}T12:00:00`).toLocaleDateString(english ? 'en-US' : 'pt-BR')}: ${count}`} className={count >= 4 ? 'aspect-square rounded-sm bg-primary' : count >= 2 ? 'aspect-square rounded-sm bg-primary/65' : count ? 'aspect-square rounded-sm bg-primary/30' : 'aspect-square rounded-sm bg-muted'} />)}</div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>{english ? 'Less' : 'Menos'}</span><span>{english ? 'More activity' : 'Mais atividade'}</span></div></>;
}

export function DashboardPage() {
  const [period, setPeriod] = useState<DashboardPeriod>('week');
  const data = useDashboardData();
  const insights = useDashboardInsights(period);
  const modules = useDashboardModules();
  const { language } = useTranslation();
  const english = language === 'en-US';
  const stats = data.data?.stats;
  const info = insights.data;
  const progress = useMemo(() => info?.totalTasks ? Math.round((info.completedTasks / info.totalTasks) * 100) : 0, [info]);
  const periods = english ? [['today', 'Today'], ['week', 'Week'], ['month', 'Month'], ['year', 'Year']] : [['today', 'Hoje'], ['week', 'Semana'], ['month', 'Mês'], ['year', 'Ano']];
  const cards = [{ label: 'Roadmaps', value: stats?.totalRoadmaps ?? 0, icon: FolderKanban, description: english ? 'Local projects' : 'Projetos locais' }, { label: english ? 'In progress' : 'Em andamento', value: stats?.activeRoadmaps ?? 0, icon: Gauge, description: english ? 'Currently moving' : 'Em progresso agora' }, { label: english ? 'Completed' : 'Concluídos', value: stats?.completedRoadmaps ?? 0, icon: CheckCircle2, description: english ? 'Finished goals' : 'Metas finalizadas' }, { label: english ? 'Favorites' : 'Favoritos', value: info?.favorites.length ?? 0, icon: Star, description: english ? 'Quick access' : 'Acesso rápido' }, { label: english ? 'Tasks' : 'Tarefas', value: info?.totalTasks ?? 0, icon: ListTodo, description: english ? 'In this workspace' : 'Neste workspace' }, { label: english ? 'Archived' : 'Arquivados', value: stats?.archivedRoadmaps ?? 0, icon: FolderArchive, description: english ? 'Preserved projects' : 'Projetos preservados' }];
  return <section className="mx-auto flex w-full max-w-6xl flex-col gap-6 pb-8"><header className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm text-muted-foreground"><LayoutDashboard className="h-4 w-4" />{english ? 'Overview' : 'Visão geral'}</div><h1 className="mt-2 text-3xl font-semibold">Dashboard</h1><p className="mt-1 text-muted-foreground">{english ? 'Welcome back. Here is what matters now.' : 'Bem-vindo de volta. Aqui está o que importa agora.'}</p></div><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-lg border bg-card p-1">{periods.map(([value, label]) => <Button key={value} size="sm" variant={period === value ? 'secondary' : 'ghost'} onClick={() => setPeriod(value as DashboardPeriod)}>{label}</Button>)}</div><Button size="icon" variant="outline" aria-label={english ? 'Notifications' : 'Notificações'}><Bell className="h-4 w-4" /></Button><Button asChild><Link to="/projects"><Plus className="h-4 w-4" />{english ? 'New roadmap' : 'Novo roadmap'}</Link></Button></div></header>
    <details className="rounded-lg border bg-card px-4 py-3"><summary className="cursor-pointer text-sm font-medium">{english ? 'Customize modules' : 'Personalizar módulos'}</summary><div className="mt-3 flex flex-wrap gap-2">{(Object.keys(dashboardModuleLabels) as Array<keyof typeof dashboardModuleLabels>).map((module) => <Button key={module} size="sm" variant={modules.visible(module) ? 'secondary' : 'outline'} onClick={() => modules.toggle(module)}>{modules.visible(module) ? (english ? 'Hide' : 'Ocultar') : (english ? 'Show' : 'Mostrar')} {english ? ({ stats: 'Stats', progress: 'Progress', activity: 'Recent activity', recent: 'Recent roadmaps', favorites: 'Favorites', tasks: 'Today tasks', productivity: 'Productivity', goals: 'Goals', actions: 'Quick actions' }[module]) : dashboardModuleLabels[module]}</Button>)}</div></details>
    {modules.visible('stats') ? <Stats loading={data.isLoading || insights.isLoading} cards={cards} /> : null}
    <div className="grid gap-4 lg:grid-cols-5">{modules.visible('progress') ? <Module title={english ? 'Overall progress' : 'Progresso geral'} description={english ? 'Based on completed tasks and subtasks.' : 'Baseado nas tarefas e subtarefas concluídas.'} className="lg:col-span-3"><div className="flex items-end justify-between"><div><p className="text-4xl font-semibold tabular-nums">{progress}%</p><p className="mt-1 text-sm text-muted-foreground">{english ? 'of registered work completed' : 'do trabalho registrado concluído'}</p></div><Trophy className="h-8 w-8 text-primary" /></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all duration-500" style={{ width: `${progress}%` }} /></div><div className="mt-5 grid grid-cols-3 gap-3 text-sm"><div><p className="font-semibold">{stats?.completedRoadmaps ?? 0}/{stats?.totalRoadmaps ?? 0}</p><p className="text-xs text-muted-foreground">Roadmaps</p></div><div><p className="font-semibold">{info?.completedTasks ?? 0}/{info?.totalTasks ?? 0}</p><p className="text-xs text-muted-foreground">{english ? 'Tasks' : 'Tarefas'}</p></div><div><p className="font-semibold">{info?.completedSubtasks ?? 0}/{info?.totalSubtasks ?? 0}</p><p className="text-xs text-muted-foreground">{english ? 'Subtasks' : 'Subtarefas'}</p></div></div></Module> : null}{modules.visible('actions') ? <Module title={english ? 'Quick actions' : 'Ações rápidas'} className="lg:col-span-2"><div className="grid gap-2"><Button asChild variant="secondary"><Link to="/projects"><Plus className="h-4 w-4" />{english ? 'New roadmap' : 'Novo roadmap'}</Link></Button><Button asChild variant="outline"><Link to="/settings"><FileJson className="h-4 w-4" />{english ? 'Import JSON' : 'Importar JSON'}</Link></Button><Button asChild variant="outline"><Link to="/settings"><Settings2 className="h-4 w-4" />{english ? 'Settings' : 'Configurações'}</Link></Button></div></Module> : null}</div>
    <div className="grid gap-4 xl:grid-cols-2">{modules.visible('recent') ? <Module title={english ? 'Recent roadmaps' : 'Roadmaps recentes'} description={english ? 'Continue where you left off.' : 'Continue de onde parou.'}><div className="space-y-3">{info?.recent.map((roadmap) => { const category = categoryBadgeMeta(roadmap.category); const value = progressBadgeMeta(roadmap.progress); return <div className="flex items-center gap-3" key={roadmap.id}><span className="h-8 w-1 rounded-full" style={{ backgroundColor: roadmap.accentColor }} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{roadmap.title}</p><div className="mt-1 flex gap-1"><Badge size="sm" variant="category" label={category.label} color={category.color} /><Badge size="sm" variant="progress" label={value.label} color={value.color} /></div></div><Button asChild size="sm" variant="ghost"><Link to={`/project/${roadmap.id}`}>{english ? 'Continue' : 'Continuar'}</Link></Button></div>; }) ?? <p className="text-sm text-muted-foreground">{english ? 'No recent roadmaps.' : 'Nenhum roadmap recente.'}</p>}</div></Module> : null}{modules.visible('favorites') ? <Module title={english ? 'Favorites' : 'Favoritos'} description={english ? 'Projects marked for quick access.' : 'Projetos marcados para acesso rápido.'}><div className="space-y-3">{info?.favorites.map((roadmap) => { const category = categoryBadgeMeta(roadmap.category); const status = statusBadgeMeta(roadmap.status); return <Link className="flex items-center gap-3 rounded-lg p-2 hover:bg-muted" to={`/project/${roadmap.id}`} key={roadmap.id}><Heart className="h-4 w-4 fill-current text-destructive" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{roadmap.title}</p><div className="mt-1 flex gap-1"><Badge size="sm" variant="category" label={category.label} color={category.color} /><Badge size="sm" variant="status" label={status.label} color={status.color} /></div></div><span className="text-sm font-semibold">{roadmap.progress}%</span></Link>; }) ?? <p className="text-sm text-muted-foreground">{english ? 'No favorites yet.' : 'Nenhum favorito ainda.'}</p>}</div></Module> : null}</div>
    <div className="grid gap-4 xl:grid-cols-5">{modules.visible('tasks') ? <Module title={english ? 'Today tasks' : 'Tarefas do dia'} description={english ? 'Sorted by priority and due date.' : 'Ordenadas por prioridade e prazo.'} className="xl:col-span-3"><div className="space-y-2">{info?.tasks.map((task) => { const priority = priorityBadgeMeta(task.priority); return <Link to={`/project/${task.roadmapId}/kanban`} className="flex items-center gap-3 rounded-lg p-2 hover:bg-muted" key={task.id}><span className="h-4 w-4 rounded border" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{task.title}</p><p className="truncate text-xs text-muted-foreground">{task.roadmapTitle} · {task.phaseTitle}</p></div><Badge size="sm" variant="priority" label={priority.label} color={priority.color} /></Link>; }) ?? <p className="text-sm text-muted-foreground">{english ? 'No pending tasks.' : 'Nenhuma tarefa pendente.'}</p>}</div></Module> : null}{modules.visible('productivity') ? <Module title={english ? 'Productivity' : 'Produtividade'} description={english ? 'Activity from the last 35 days.' : 'Atividade dos últimos 35 dias.'} className="xl:col-span-2"><Productivity activity={info?.productivity ?? []} english={english} /></Module> : null}</div>
    <div className="grid gap-4 xl:grid-cols-2">{modules.visible('activity') ? <Module title={english ? 'Recent activity' : 'Atividade recente'} description={english ? 'Latest workspace changes.' : 'Últimas alterações no workspace.'}><div className="space-y-3">{info?.activity.slice(0, 6).map((item) => <Link to={item.roadmapId ? `/project/${item.roadmapId}` : '/projects'} className="flex gap-3 rounded-lg p-1 hover:bg-muted" key={item.id}><Clock3 className="mt-0.5 h-4 w-4 text-primary" /><div><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.occurredAt).toLocaleString(english ? 'en-US' : 'pt-BR')} · {item.roadmapTitle ?? (english ? 'Workspace' : 'Workspace')}</p></div></Link>) ?? <p className="text-sm text-muted-foreground">{english ? 'New activity will appear here.' : 'As próximas alterações aparecerão aqui.'}</p>}</div></Module> : null}{modules.visible('goals') ? <Module title={english ? 'Weekly goals' : 'Metas da semana'} description={english ? 'A simple view to keep momentum.' : 'Uma leitura simples para manter o ritmo.'}><div className="space-y-5">{[{ label: english ? 'Complete tasks' : 'Concluir tarefas', value: info?.completedTasks ?? 0, total: Math.max(10, info?.totalTasks ?? 0), icon: Target }, { label: english ? 'Complete roadmaps' : 'Concluir roadmaps', value: stats?.completedRoadmaps ?? 0, total: Math.max(3, stats?.totalRoadmaps ?? 0), icon: Goal }].map((goal) => { const percent = Math.min(100, Math.round((goal.value / goal.total) * 100)); const Icon = goal.icon; return <div key={goal.label}><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 font-medium"><Icon className="h-4 w-4 text-primary" />{goal.label}</span><span className="text-muted-foreground">{goal.value}/{goal.total}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${percent}%` }} /></div></div>; })}</div></Module> : null}</div>
  </section>;
}
